// Query-key factory. Keep every key here so ws.ts can invalidate precisely.
export const qk = {
  me: ['me'] as const,
  myChips: (f: Record<string, unknown> = {}) => ['me', 'chips', f] as const,
  grid: ['me', 'grid'] as const,
  activity: ['me', 'activity'] as const,
  pending: ['me', 'pending'] as const,
  packs: ['packs'] as const,
  quote: (sku: number, qty: number, currency: string) => ['packs', 'quote', sku, qty, currency] as const,
  packOpen: (sig: string) => ['packs', 'opens', sig] as const,
  packVerify: (sig: string) => ['packs', 'verify', sig] as const,
  collections: ['collections'] as const,
  archetype: (c: number, r: number) => ['collections', c, r] as const,
  chip: (asset: string) => ['chips', asset] as const,
  listings: (f: Record<string, unknown> = {}) => ['market', 'listings', f] as const,
  floor: ['market', 'floor'] as const,
  history: (f: Record<string, unknown> = {}) => ['market', 'history', f] as const,
  offers: (dir: string) => ['market', 'offers', dir] as const,
  recipes: ['fusion', 'recipes'] as const,
  suggest: (protect: boolean) => ['fusion', 'suggest', protect] as const,
  arenaMe: ['arena', 'me'] as const,
  season: ['arena', 'season'] as const,
  match: (id: string) => ['arena', 'match', id] as const,
  stakingOverview: ['staking', 'overview'] as const,
  stakingMe: ['staking', 'me'] as const,
  quests: ['quests'] as const,
  human: ['me', 'human'] as const,
  claims: ['quests', 'claims'] as const,
  streak: ['quests', 'streak'] as const,
  leaderboard: (board: string, season?: number) => ['leaderboard', board, season ?? 'current'] as const,
};
