/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/siws/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a SIWS nonce for a wallet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        address: components["schemas"]["Pubkey"];
                    };
                };
            };
            responses: {
                /** @description nonce */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            nonce?: string;
                            statement?: string;
                            /** Format: date-time */
                            expiresAt?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/siws/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify signed SIWS message, start session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        address: components["schemas"]["Pubkey"];
                        message: string;
                        /** @description base58 */
                        signature: string;
                        referrer?: components["schemas"]["Pubkey"];
                        fingerprint?: string;
                    };
                };
            };
            responses: {
                /** @description session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            csrf?: string;
                            wallet?: components["schemas"]["WalletProfile"];
                        };
                    };
                };
                /** @description siws_address | siws_nonce | siws_expired | siws_domain | siws_issued_at | siws_signature */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile, balances, pity, flags */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/chips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inventory (projection of Core owner + ChipState) */
        get: {
            parameters: {
                query?: {
                    collection?: number;
                    rarity?: number;
                    status?: "free" | "staked" | "listed" | "locked" | "fusing";
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description chips */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChipPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 10×9 collection grid — owned count per (collection, rarity) + completed sets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description grid */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description [collection][rarity] → owned count */
                            cells?: number[][];
                            completedSets?: number;
                            missingForSet?: {
                                collection?: number;
                                rarities?: number[];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unified activity feed (pack opens, fusions, sales, claims, matches) */
        get: {
            parameters: {
                query?: {
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description feed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** In-flight commit-reveal operations (packs / fusions) with crank status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description pending */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            packs?: components["schemas"]["PendingPack"][];
                            fusions?: components["schemas"]["PendingFusion"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/handle/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is this handle free? (also returns the ref_hash to commit on-chain)
         * @description ref_hash = keccak256(0x00 ‖ kind:u8 ‖ wallet:32 ‖ lowercase(handle) utf8). The client passes it to
         *     chip_core::pay_service(kind=Handle|HandleChange, …). Reserved 120 s for the caller once checked.
         */
        get: {
            parameters: {
                query: {
                    handle: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description availability */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            available?: boolean;
                            /** @enum {string} */
                            reason?: "taken" | "reserved" | "blocked" | "cooldown";
                            /** @description 0 first handle, 1 change */
                            kind?: number;
                            /** @description hex, 32 bytes */
                            refHash?: string;
                            priceUsdCents?: number;
                            /** Format: date-time */
                            reservedUntil?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/handle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Claim a handle after paying on-chain (pay_service kind 0/1) — signature required
         * @description The indexer verifies the ServicePaid event in `signature`: buyer == caller, kind ∈ {0,1}, ref_hash matches
         *     keccak(kind ‖ wallet ‖ lowercase(handle)), payment not previously consumed. $CG payments are burned on-chain;
         *     SOL/USDC/SKR go to the treasury. Handle changes are limited to 1 per 30 days; released handles are quarantined 90 days.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        handle: string;
                        signature: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description payment not found / already consumed */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description handle_taken / handle_cooldown / same_handle — or payment_pending: the payment is confirmed but not yet finalized (SEC-M5); retry in ~30 s */
                409: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owned entitlements (skins, themes, emotes, season pass, instant reveal…) and daily-cap status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description entitlements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entitlements?: components["schemas"]["Entitlement"][];
                            dailyLeft?: {
                                [key: string]: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue of paid services (mirrors economy ServiceKind) with live quotes in every currency */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description catalogue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            services?: components["schemas"]["Service"][];
                            solUsd?: number;
                            skrUsd?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind a paid ServicePaid event to an entitlement payload (skins → asset, theme id, emote pack id, …) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        signature: string;
                        kind: number;
                        /** @description canonical JSON; keccak(kind ‖ wallet ‖ canonical(payload)) must equal ref_hash */
                        payload: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description entitlement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Entitlement"];
                    };
                };
                /** @description payment not found / mismatch */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not_owner — or payment_pending: the payment is confirmed but not yet finalized (SEC-M5); retry in ~30 s */
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog with live odds, floors, pity and caps (from GameConfig) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description catalog */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            paramsVersion?: number;
                            packs?: components["schemas"]["PackSku"][];
                            bundles?: {
                                qty?: number;
                                discountBps?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price quote + everything needed to build buy_pack
         * @description Returns the SOL / SKR amount computed from the studio's own Pyth push-oracle accounts (shard 0xCA75, posted by
         *     our price pusher — ops/pyth-pusher/) with the exact integer formula of chip_core::units_for_cents, the 1 %
         *     slippage guard (`maxLamports`), the `priceUpdateAccount` the client must pass to buy_pack, $CG/USDC amounts,
         *     the caller's effective odds (pity applied), the Switchboard queue and the PDA set. Bundle and SKR promo
         *     discounts are stacked additively and capped at 30 %.
         *     The quote is never synthesised: if the on-chain price is older than 45 s (60 s max age minus the 15 s a buyer
         *     needs to sign) or the account is missing/unverified the endpoint answers **503 price_unavailable** and the
         *     client hides that rail. `expiresAt` is when the current on-chain update would fail the age check.
         *     `pythUpdateData` is always empty in the push model (kept for a future pull-model fallback).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sku: number;
                        qty: number;
                        /** @enum {string} */
                        currency: "SOL" | "USDC" | "CG" | "SKR";
                    };
                };
            };
            responses: {
                /** @description quote */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PackQuote"];
                    };
                };
                400: components["responses"]["Error"];
                /** @description sign-in required (pity and caps are per wallet) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description starter_claimed — one Starter per wallet */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description daily_cap — Limited 5 / day */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description price_unavailable — Pyth account stale / missing / unverified, or its confidence interval is wider than 2 % of the price (SEC-M2 — the program would reject with PriceUncertain); retry after the next push (≤ 30 s) */
                503: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health of the price cache the API quotes from (what our Pyth pusher last posted and how old it is) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description prices */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 60 */
                            maxAgeS?: number;
                            /** @example 45 */
                            alertAgeS?: number;
                            feeds?: {
                                [key: string]: {
                                    usd?: number;
                                    account?: components["schemas"]["Pubkey"];
                                    /** Format: date-time */
                                    publishTime?: string;
                                    ageS?: number;
                                    confBps?: number;
                                    /** Format: date-time */
                                    cachedAt?: string;
                                    healthy?: boolean;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness of the indexer, the price cache, the crank queue, the on-chain pause state per program (SEC-H2) and the burn oracle (SEC-M1) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            /** @description newest indexed slot */
                            lastSlot?: number;
                            /** @description same shape as GET /prices */
                            prices?: Record<string, never>;
                            crank?: {
                                pending?: number;
                                stale?: number;
                                settled?: number;
                                closed?: number;
                                abandoned?: number;
                                headAgeS?: number | null;
                                healthy?: boolean;
                            };
                            /** @description latest PauseChanged per program (chip_core / staking / arena); absent key = never changed since genesis */
                            paused?: {
                                [key: string]: {
                                    paused?: boolean;
                                    by?: components["schemas"]["Pubkey"];
                                    slot?: number;
                                    blockTime?: number | null;
                                };
                            };
                            /** @description SEC-M5 reconciler — how far the event log lags finalization; dropped (forked) transactions are evicted and projections rebuilt */
                            finality?: {
                                /** @description FINALITY_ASSUME=1 dev shortcut (refused in production) */
                                assume?: boolean;
                                pendingSignatures?: number;
                                oldestPendingAgeS?: number | null;
                                /** Format: date-time */
                                lastFinalizedAt?: string | null;
                                /** @description nothing waiting longer than 10 min */
                                healthy?: boolean;
                            };
                            /** @description SEC-M1 keeper that feeds staking.report_burn from indexed burns (hourly) */
                            burnOracle?: {
                                lastSignature?: string | null;
                                lastAmountMicro?: string | null;
                                lastReportAgeS?: number | null;
                                reportedTotalMicro?: string;
                                /** @description burns indexed but not yet reported */
                                pendingMicro?: string;
                                pendingRows?: number;
                                /** @description reported within 3 intervals */
                                healthy?: boolean;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/opens/{signature}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result of a pack open (poll after reveal; WS pushes the same payload) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    signature: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PackOpenResult"];
                    };
                };
                /** @description not revealed yet */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingPack"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provably-fair verifier — recompute a pack result from its randomness bytes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        signature: string;
                    };
                };
            };
            responses: {
                /** @description verification */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            randomnessAccount?: components["schemas"]["Pubkey"];
                            rollHex?: string;
                            pityBefore?: number;
                            effectiveOddsBps?: number[];
                            recomputed?: components["schemas"]["RolledChip"][];
                            onChain?: components["schemas"]["RolledChip"][];
                            matches?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All 10 districts with lore, art, element, mint stats, floor per rarity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Collection"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{idx}/chips/{rarity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chip archetype page (lore, art, supply, floor, recent sales) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    idx: number;
                    rarity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description archetype */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChipArchetype"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chips/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single chip — state, owner, listing, provenance (pack/fusion event) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset: components["schemas"]["Pubkey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description chip */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChipDetail"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active listings with filters */
        get: {
            parameters: {
                query?: {
                    collection?: number;
                    rarity?: number;
                    rarityMin?: number;
                    indexMin?: number;
                    indexMax?: number;
                    levelMin?: number;
                    currency?: "SOL" | "USDC" | "SKR";
                    priceMaxUsd?: number;
                    /** @description auth required; only chips that complete one of my sets */
                    missingForMySet?: boolean;
                    sort?: "price_asc" | "price_desc" | "newest" | "rarity_desc" | "index_asc";
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description listings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/floor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Floor matrix 10×9 (USD-normalized) + 24 h volume; cached 30 s */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description floors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            asOf?: string;
                            solUsd?: number;
                            skrUsd?: number;
                            floors?: (number | null)[][];
                            listedCount?: number[][];
                            volume24hUsd?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sales history (per chip, archetype, or global) */
        get: {
            parameters: {
                query?: {
                    asset?: components["schemas"]["Pubkey"];
                    collection?: number;
                    rarity?: number;
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalePage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offers made by me / received on my chips */
        get: {
            parameters: {
                query?: {
                    direction?: "made" | "received";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description offers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Offer"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fusion/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All 8 recipes (rule, success %, fee, lock) — mirrors on-chain constants */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description recipes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recipe"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fusion/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a material set, return success %, fee, result preview and accounts for `fuse` */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        materials: components["schemas"]["Pubkey"][];
                        resultCollection?: number;
                        useBooster?: boolean;
                    };
                };
            };
            responses: {
                /** @description plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FusionPlan"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fusion/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auto-pick fusable triples from my inventory (never touches staked/listed/locked/set-critical chips) */
        get: {
            parameters: {
                query?: {
                    protectSets?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description suggestions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FusionPlan"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enter matchmaking with a squad + seed commit */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        squad: components["schemas"]["Pubkey"][];
                        /** @description hex sha256(nonce) */
                        commit: string;
                        wagerCgMicro?: string;
                    };
                };
            };
            responses: {
                /** @description queued (or paired at once — `matchId` set) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ticket?: string;
                            league?: number;
                            squadPower?: number;
                            synergy?: number;
                            estimatedWaitSec?: number;
                            wsChannel?: string;
                            matchId?: string | null;
                        };
                    };
                };
                /** @description chip busy (listed / fusing) or a match is still awaiting your reveal (`match_pending`) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description bad squad (not 3 distinct owned chips */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Leave queue (no-op once matched) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/matches/{id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal the seed nonce (hex; sha256(nonce) must equal your commit). When both sides revealed the server resolves at once — seed = sha256(matchId ‖ nonceA ‖ nonceB ‖ serverSecret); a side that never reveals forfeits after ARENA_REVEAL_TIMEOUT_S (120 s) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description hex, 8..64 bytes */
                        nonce: string;
                    };
                };
            };
            responses: {
                /** @description accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            /** @enum {string} */
                            status?: "revealing" | "resolved" | "cancelled";
                            matchId?: string;
                            resolved?: boolean;
                            winner?: string;
                            /** @enum {string} */
                            waitingFor?: "a" | "b";
                        };
                    };
                };
                /** @description bad nonce / commit mismatch */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not a player of this match */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description a different nonce was already revealed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/matches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match record incl. seed derivation (nonces/seed hidden until both revealed; the season secret appears after the season ends). Wager battles are listed under their battle PDA once the resolver settled them. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description match */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Match"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My rating, league, streak, daily rewarded matches left, wager battles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArenaMe"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/seasons/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season timer, pool size, payout brackets, server-secret hash (and the previous season's revealed secret) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description season */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Season"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deterministic fight preview for the squad builder (no rewards; same engine as live). Each side is 3 asset keys or 3 `{collection, rarity, level}` specs. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        squadA: components["schemas"]["FighterSpec"][];
                        squadB: components["schemas"]["FighterSpec"][];
                    };
                };
            };
            responses: {
                /** @description win probability + sample rounds */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pWinA?: number;
                            powerA?: number;
                            powerB?: number;
                            fightPowerA?: number;
                            fightPowerB?: number;
                            synergyA?: number;
                            synergyB?: number;
                            leagueA?: number;
                            leagueB?: number;
                            elementEdges?: string[];
                            sampleRounds?: components["schemas"]["Round"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staking/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pools (TVL, weight, today's budget), implied APY per tier, emission day stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StakingOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staking/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My token stakes, chip stakes, pending rewards (ESTIMATE from indexed DayClosed budgets — the exact figure is the on-chain accumulator the client reads directly), set bonus status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description mine */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StakingMe"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staking/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** APY estimate for an amount/tier given current pool weight */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        amountCgMicro: string;
                        tier: number;
                    };
                };
            };
            responses: {
                /** @description estimate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            apyPct?: number;
                            dailyCgMicro?: string;
                            /** Format: date-time */
                            unlockAt?: string;
                            earlyExitPenaltyBps?: number;
                            boostBps?: number;
                            minStakeCgMicro?: string;
                            indicativeApyRange?: number[];
                            /** @enum {string} */
                            emissionSource?: "chain" | "schedule";
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active quests with my progress (counted from indexed events; reading this endpoint records today's login); eligibility reason (account age / paid pack / rewards paused) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description quests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Quest"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quests/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record today's login explicitly (idempotent; `GET /quests` does it too) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            day?: number;
                            inserted?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quests/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Merkle leaves (root, amount, proof) built by the reward oracle. `currency` follows the root kind — 2..4 pay $CG via `claim_root`, 5..7 pay SKR via `claim_skr_root`. `claimableAt` is null until the root is published on chain (then published_at + 1 h timelock). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description claims */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimLeaf"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/skr-pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SKR prize-pool ledger (funded / withdrawn / paid / reserved) and live SKR roots — public proof that SKR rewards never exceed treasury funding */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description pool */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkrPool"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quests/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily streak state (consecutive days with all four $CG dailies done) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description streak */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            days?: number;
                            nextChipAt?: number;
                            /** Format: date-time */
                            resetsAt?: string;
                            todayDone?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/{board}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season rating / collection score / staking weight / fusion count boards */
        get: {
            parameters: {
                query?: {
                    season?: number;
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path: {
                    board: "rating" | "collection" | "staking" | "fusion";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description rows */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current on-chain GameConfig + EmissionState + history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description params */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Propose a params change → validates guard-rails → creates Squads proposal (48 h timelock) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        packs?: components["schemas"]["PackSku"][];
                        marketFeeBps?: number;
                        featuredCollection?: number;
                        emissionSplitBps?: number[];
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description proposal created */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description guard-rail violation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the economy model (packages/economy) with overridden assumptions/params */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description report json */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause a program (chip_core / staking / arena) — 2 admin approvals */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        program: string;
                        paused: boolean;
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fraud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fraud signals queue */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description rows */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fraud/{wallet}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve — ignore / shadow ban / pause rewards / ban (audited) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wallet: components["schemas"]["Pubkey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PRD KPI dashboard (D1/D7/D30, ARPPU, conversion, sink ratio, floor index) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description kpi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code?: string;
            message?: string;
            details?: unknown;
        };
        Pubkey: string;
        /** @description 0 Common … 8 Diamond */
        Rarity: number;
        WalletProfile: {
            address?: components["schemas"]["Pubkey"];
            handle?: string;
            avatarAsset?: components["schemas"]["Pubkey"];
            /** Format: date-time */
            firstSeen?: string;
            country?: string;
        };
        Me: components["schemas"]["WalletProfile"] & {
            balances?: {
                lamports?: string;
                usdc?: string;
                cg?: string;
                skr?: string;
            };
            pity?: {
                counters?: number[];
                toGuarantee?: number[];
                boughtToday?: number[];
                starterClaimed?: boolean;
            };
            boosters?: number;
            flags?: {
                rewardsPaused?: boolean;
                geoRestricted?: boolean;
                accountAgeH?: number;
                hasPaidPack?: boolean;
            };
            completedSets?: number;
        };
        Chip: {
            asset?: components["schemas"]["Pubkey"];
            owner?: components["schemas"]["Pubkey"];
            collection?: number;
            rarity?: components["schemas"]["Rarity"];
            level?: number;
            index?: number;
            flags?: {
                staked?: boolean;
                listed?: boolean;
                fusing?: boolean;
                soulbound?: boolean;
            };
            /** Format: date-time */
            lockUntil?: string | null;
            power?: number;
            stakeWeight?: string;
            art?: {
                /** Format: uri */
                image?: string;
                /** Format: uri */
                video?: string;
                vfxTier?: number;
            };
            listing?: components["schemas"]["Listing"];
        };
        ChipPage: {
            items?: components["schemas"]["Chip"][];
            nextCursor?: string | null;
            total?: number;
        };
        ChipDetail: components["schemas"]["Chip"] & {
            provenance?: {
                origin?: string;
                signature?: string;
                rollHex?: string;
                recipe?: number;
            };
            sales?: components["schemas"]["Sale"][];
            archetype?: components["schemas"]["ChipArchetype"];
        };
        ChipArchetype: {
            collection?: number;
            rarity?: components["schemas"]["Rarity"];
            name?: string;
            lore?: string;
            rim?: string;
            supply?: number;
            floorUsd?: number | null;
            listed?: number;
            basePower?: number;
            maxLevel?: number;
        };
        Collection: {
            idx?: number;
            symbol?: string;
            name?: string;
            /** @enum {string} */
            element?: "paint" | "steel" | "wheels" | "noise" | "shadow";
            palette?: string[];
            lore?: string;
            minted?: number;
            mintedByRarity?: number[];
            floors?: (number | null)[];
            featured?: boolean;
        };
        PackSku: {
            sku?: number;
            name?: string;
            chips?: number;
            priceUsdCents?: number;
            priceCgMicro?: string | null;
            currencies?: ("SOL" | "USDC" | "CG" | "SKR")[];
            oddsBps?: number[];
            floor?: components["schemas"]["Rarity"];
            dailyCap?: number | null;
            pity?: {
                tier?: number;
                softStart?: number;
                softStepBps?: number;
                hardAt?: number;
            } | null;
            /** @enum {string} */
            pool?: "all" | "featured";
            enabled?: boolean;
            pAtLeastLegend?: number;
            evPct?: number;
        };
        PackQuote: {
            sku?: number;
            qty?: number;
            currency?: string;
            /** @description lamports / micro-USDC / micro-CG / micro-SKR incl. bundle (and SKR promo) discount — floor(cents × 10^(decimals-2) × 10^-expo / price), same integers as the program */
            amount?: string;
            /** @description amount × 1.01 for SOL and SKR (0 otherwise); slippage guard passed to buy_pack (max_lamports = max units of the volatile currency) */
            maxLamports?: string;
            /** @description USD price after discounts (what the program converts) */
            priceUsdCents?: number;
            rentReserveLamports?: string;
            /** @description Pyth SOL/USD at quote time (from our push-oracle account) */
            solUsd?: number;
            /** @description Pyth SKR/USD at quote time (from our push-oracle account) */
            skrUsd?: number;
            /** @description age of the on-chain update used (SOL/SKR only); program rejects > 60 s */
            priceAgeS?: number;
            /** @description total discount applied (bundle + SKR promo, capped 3000) */
            discountBps?: number;
            /** @description PriceUpdateV2 account to pass as price_update (our shard 0xCA75); absent for USDC/$CG */
            priceUpdateAccount?: components["schemas"]["Pubkey"];
            /** @description always [] in the push model (our pusher posts ahead of time); reserved for a pull-model fallback */
            pythUpdateData?: string[];
            effectiveOddsBps?: number[];
            pityCounter?: number;
            hardPityIn?: number;
            nonce?: string;
            accounts?: {
                [key: string]: components["schemas"]["Pubkey"];
            };
            switchboardQueue?: components["schemas"]["Pubkey"];
            /** Format: date-time */
            expiresAt?: string;
        };
        RolledChip: {
            rarity?: components["schemas"]["Rarity"];
            collection?: number;
        };
        Service: {
            id?: string;
            kind?: number;
            name?: string;
            priceUsdCents?: number;
            dailyCap?: number;
            recurring?: boolean;
            /** @description amount in base units per currency (SOL lamports incl. 1 % guard, USDC, CG, SKR) */
            quotes?: {
                [key: string]: string;
            };
        };
        Entitlement: {
            id?: string;
            kind?: number;
            payload?: {
                [key: string]: unknown;
            };
            signature?: string;
            currency?: string;
            amount?: string;
            /** Format: date-time */
            grantedAt?: string;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        PendingPack: {
            nonce?: string;
            sku?: number;
            qty?: number;
            opened?: number;
            commitSlot?: number;
            currentSlot?: number;
            randomness?: components["schemas"]["Pubkey"];
            /** @enum {string} */
            status?: "awaiting_reveal" | "revealing" | "opening" | "stale";
            /** Format: date-time */
            staleAt?: string;
        };
        PendingFusion: {
            nonce?: string;
            recipe?: number;
            materials?: components["schemas"]["Pubkey"][];
            boosted?: boolean;
            status?: string;
        };
        PackOpenResult: {
            signature?: string;
            sku?: number;
            chips?: components["schemas"]["Chip"][];
            rollHex?: string;
            pityBefore?: number;
            pityAfter?: number;
            highlights?: {
                bestRarity?: components["schemas"]["Rarity"];
                newForSet?: number[];
                completedSet?: number | null;
            };
        };
        Listing: {
            asset?: components["schemas"]["Pubkey"];
            seller?: components["schemas"]["Pubkey"];
            price?: string;
            /** @enum {string} */
            currency?: "SOL" | "USDC" | "SKR";
            priceUsd?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ListingPage: {
            items?: (components["schemas"]["Listing"] & {
                chip?: components["schemas"]["Chip"];
            })[];
            nextCursor?: string | null;
            total?: number;
        };
        Sale: {
            asset?: components["schemas"]["Pubkey"];
            seller?: components["schemas"]["Pubkey"];
            buyer?: components["schemas"]["Pubkey"];
            price?: string;
            currency?: string;
            priceUsd?: number;
            fee?: string;
            royalty?: string;
            signature?: string;
            /** Format: date-time */
            blockTime?: string;
        };
        SalePage: {
            items?: components["schemas"]["Sale"][];
            nextCursor?: string | null;
        };
        Offer: {
            asset?: components["schemas"]["Pubkey"];
            bidder?: components["schemas"]["Pubkey"];
            amountUsdc?: string;
            /** Format: date-time */
            expiresAt?: string;
            chip?: components["schemas"]["Chip"];
        };
        Recipe: {
            from?: components["schemas"]["Rarity"];
            to?: components["schemas"]["Rarity"];
            /** @enum {string} */
            rule?: "any" | "same-collection";
            successBps?: number;
            refundOnFail?: number;
            feeCgMicro?: string;
            resultLockSeconds?: number;
            boosterBonusBps?: number;
            boosterCapBps?: number;
        };
        FusionPlan: {
            materials?: components["schemas"]["Chip"][];
            recipe?: components["schemas"]["Recipe"];
            resultCollection?: number;
            resultRarity?: components["schemas"]["Rarity"];
            successBps?: number;
            feeCgMicro?: string;
            breaksSet?: boolean;
            warnings?: string[];
            nonce?: string;
            accounts?: {
                [key: string]: components["schemas"]["Pubkey"];
            };
            needsRandomness?: boolean;
        };
        /** @description A chip by asset key (must be indexed) or by stats */
        FighterSpec: components["schemas"]["Pubkey"] | {
            collection: number;
            rarity: number;
            level?: number;
        };
        /** @description effA = chipPower × synergyA × (1 + elementEdge) × luckA; effB = chipPower × synergyB × luckB; luck ~ U[0.5, 1.5] from the seed */
        Round: {
            lane?: number;
            attacker?: string;
            defender?: string;
            elementEdge?: number;
            luckA?: number;
            luckB?: number;
            effA?: number;
            effB?: number;
            winner?: string;
        };
        Match: {
            id?: string;
            season?: number;
            a?: components["schemas"]["Pubkey"];
            /** @description opponent wallet, or `bot:<league>` for a bot fill */
            b?: string;
            squadA?: components["schemas"]["Chip"][];
            squadB?: components["schemas"]["Chip"][];
            powerA?: number;
            powerB?: number;
            league?: number;
            commitA?: string;
            commitB?: string;
            nonceA?: string | null;
            nonceB?: string | null;
            /** @description hex sha256(matchId ‖ nonceA ‖ nonceB ‖ serverSecret); null until resolved */
            seed?: string | null;
            seedFormula?: string;
            rounds?: components["schemas"]["Round"][];
            winner?: string | null;
            /** @enum {string} */
            status?: "revealing" | "resolved" | "cancelled";
            forfeit?: boolean;
            bot?: boolean;
            wagerCgMicro?: string;
            battlePda?: string | null;
            resolveSignature?: string | null;
            rewarded?: boolean;
            rewardA?: string;
            rewardB?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string | null;
            serverSecretHash?: string | null;
            /** @description published once the season ended → anyone can re-run the fight */
            serverSecret?: string | null;
        };
        ArenaMe: {
            rating?: number;
            rd?: number;
            league?: number;
            games?: number;
            wins?: number;
            streak?: number;
            rewardedMatchesLeft?: number;
            seasonRank?: number | null;
            projectedBracket?: string | null;
            season?: number;
            openBattles?: {
                battle?: string;
                wagerCgMicro?: string;
                status?: string;
                powerA?: number;
                league?: number;
                createdAt?: string | null;
            }[];
            currentMatch?: {
                id?: string;
                opponent?: string;
                iRevealed?: boolean;
                /** Format: date-time */
                revealDeadline?: string;
            } | null;
            queue?: {
                ticket?: string;
                league?: number;
                /** Format: date-time */
                joinedAt?: string;
            } | null;
            recent?: {
                id?: string;
                opponent?: string;
                won?: boolean;
                forfeit?: boolean;
                reward?: string;
                endedAt?: string | null;
            }[];
            /** @description match rewards not yet in a published root */
            pendingRewardMicro?: string;
        };
        Season: {
            id?: number;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            poolCgMicro?: string;
            brackets?: {
                topPct?: number;
                sharePct?: number;
            }[];
            serverSecretHash?: string;
            serverSecret?: string | null;
            previous?: {
                id?: number;
                serverSecretHash?: string;
                serverSecret?: string | null;
            } | null;
            weeks?: number;
            chipRewardByLeague?: string[];
            soulboundDays?: number;
        };
        StakingOverview: {
            emission?: {
                dayIndex?: number;
                year?: number;
                scheduleCapMicro?: string;
                guardedMicro?: string;
                burn7dAvgMicro?: string;
                mintedTotalMicro?: string;
                splitBps?: number[];
                /**
                 * @description schedule = no DayClosed indexed yet (30 % floor assumed)
                 * @enum {string}
                 */
                source?: "chain" | "schedule";
            };
            tokenPool?: {
                tvlMicro?: string;
                totalWeight?: string;
                budgetTodayMicro?: string;
                apyByTier?: number[];
            };
            chipPool?: {
                stakedChips?: number;
                totalWeight?: string;
                budgetTodayMicro?: string;
                dailyPerWeightUnit?: string;
            };
        };
        StakingMe: {
            tokenStakes?: {
                tier?: number;
                amount?: string;
                weight?: string;
                pending?: string;
                /** Format: date-time */
                unlockAt?: string;
                earlyExitPenalty?: string;
            }[];
            chipStakes?: {
                chip?: components["schemas"]["Chip"];
                weight?: string;
                pending?: string;
                /** Format: date-time */
                since?: string;
            }[];
            setBonus?: {
                onChainSets?: number;
                computedSets?: number;
                multBps?: number;
                syncPending?: boolean;
            };
            totalPendingMicro?: string;
            pendingEstimated?: boolean;
        };
        Quest: {
            id?: string;
            cadence?: string;
            title?: string;
            description?: string;
            metric?: string;
            target?: number;
            value?: number;
            rewardCgMicro?: string;
            rewardChip?: Record<string, never> | null;
            rewardBooster?: number;
            completedAt?: string | null;
            /** @description done and waiting for the next reward root */
            claimable?: boolean;
            rooted?: boolean;
            /** @description micro-$CG actually credited after daily/weekly caps */
            creditedCgMicro?: string | null;
            ineligibleReason?: string | null;
            /** Format: date-time */
            resetsAt?: string | null;
        };
        ClaimLeaf: {
            /** @description 2 quests · 3 PvP season · 4 events ($CG, minted from emission) · 5 quests · 6 season · 7 events (SKR, prize pool) */
            kind?: number;
            epoch?: number;
            /** @enum {string} */
            currency?: "CG" | "SKR";
            rootPda?: components["schemas"]["Pubkey"];
            amountMicro?: string;
            proof?: string[];
            root?: string;
            /** Format: date-time */
            claimableAt?: string | null;
            claimed?: boolean;
            published?: boolean;
            /** @description which quests / matches the leaf pays */
            memo?: unknown;
        };
        SkrPool: {
            fundedTotalMicro?: string;
            withdrawnTotalMicro?: string;
            paidTotalMicro?: string;
            /** @description budget locked in live (non-revoked) roots minus what was already claimed */
            reservedMicro?: string;
            /** @description funded − withdrawn − paid − reserved; what new roots can still draw */
            budgetMicro?: string;
            maxRootBudgetMicro?: string | null;
            paused?: boolean;
            roots?: {
                kind?: number;
                epoch?: number;
                budgetMicro?: string;
                claimedMicro?: string;
                revoked?: boolean;
                slot?: number;
            }[];
            /** @description Treasury funding policy audit — realised SKR revenue (opened packs, settled SKR sales' treasury fee part, SKR services) × published shares (15 / 10 / 5 %) vs. what was actually funded */
            funding?: {
                treasuryWallet?: components["schemas"]["Pubkey"];
                policyBps?: {
                    packRevenue?: number;
                    marketFeeTreasury?: number;
                    servicesRevenue?: number;
                };
                cadence?: string;
                revenue?: {
                    packRevenueMicro?: string;
                    marketFeeTreasuryMicro?: string;
                    servicesRevenueMicro?: string;
                };
                /** @description Σ revenue × share — what the policy says should have been funded to date */
                dueMicro?: string;
                dueBreakdownMicro?: {
                    packs?: string;
                    market?: string;
                    services?: string;
                };
                /** @description fundedTotal − due; negative means the treasury is behind on the published policy */
                surplusMicro?: string;
            };
        };
        LeaderboardPage: {
            board?: string;
            season?: number;
            me?: Record<string, never> | null;
            items?: {
                rank?: number;
                wallet?: components["schemas"]["Pubkey"];
                handle?: string;
                value?: number;
                league?: number;
                avatar?: string;
            }[];
            nextCursor?: string | null;
        };
        ActivityPage: {
            items?: {
                kind?: string;
                signature?: string;
                /** Format: date-time */
                blockTime?: string;
                payload?: unknown;
            }[];
            nextCursor?: string | null;
        };
    };
    responses: {
        /** @description error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description rate_limited — retry after `Retry-After` seconds */
        RateLimited: {
            headers: {
                /** @description seconds */
                "Retry-After"?: number;
                /** @description e.g. `10;w=60` */
                "RateLimit-Policy"?: string;
                "RateLimit-Remaining"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description opaque pagination cursor */
        cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
