/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/siws/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a SIWS nonce for a wallet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        address: components["schemas"]["Pubkey"];
                    };
                };
            };
            responses: {
                /** @description nonce */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            nonce?: string;
                            statement?: string;
                            /** Format: date-time */
                            expiresAt?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/siws/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify signed SIWS message, start session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        address: components["schemas"]["Pubkey"];
                        message: string;
                        /** @description base58 */
                        signature: string;
                        referrer?: components["schemas"]["Pubkey"];
                        fingerprint?: string;
                    };
                };
            };
            responses: {
                /** @description session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            csrf?: string;
                            wallet?: components["schemas"]["WalletProfile"];
                        };
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile, balances, pity, flags */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/chips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inventory (projection of Core owner + ChipState) */
        get: {
            parameters: {
                query?: {
                    collection?: number;
                    rarity?: number;
                    status?: "free" | "staked" | "listed" | "locked" | "fusing";
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description chips */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChipPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 10×9 collection grid — owned count per (collection, rarity) + completed sets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description grid */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description [collection][rarity] → owned count */
                            cells?: number[][];
                            completedSets?: number;
                            missingForSet?: {
                                collection?: number;
                                rarities?: number[];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unified activity feed (pack opens, fusions, sales, claims, matches) */
        get: {
            parameters: {
                query?: {
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description feed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** In-flight commit-reveal operations (packs / fusions) with crank status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description pending */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            packs?: components["schemas"]["PendingPack"][];
                            fusions?: components["schemas"]["PendingFusion"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/handle/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is this handle free? (also returns the ref_hash to commit on-chain)
         * @description ref_hash = keccak256(0x00 ‖ kind:u8 ‖ wallet:32 ‖ lowercase(handle) utf8). The client passes it to
         *     chip_core::pay_service(kind=Handle|HandleChange, …). Reserved 120 s for the caller once checked.
         */
        get: {
            parameters: {
                query: {
                    handle: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description availability */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            available?: boolean;
                            /** @enum {string} */
                            reason?: "taken" | "reserved" | "blocked" | "cooldown";
                            /** @description 0 first handle, 1 change */
                            kind?: number;
                            /** @description hex, 32 bytes */
                            refHash?: string;
                            priceUsdCents?: number;
                            /** Format: date-time */
                            reservedUntil?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/handle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Claim a handle after paying on-chain (pay_service kind 0/1) — signature required
         * @description The indexer verifies the ServicePaid event in `signature`: buyer == caller, kind ∈ {0,1}, ref_hash matches
         *     keccak(kind ‖ wallet ‖ lowercase(handle)), payment not previously consumed. $CG payments are burned on-chain;
         *     SOL/USDC/SKR go to the treasury. Handle changes are limited to 1 per 30 days; released handles are quarantined 90 days.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        handle: string;
                        signature: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description payment not found / already consumed */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owned entitlements (skins, themes, emotes, season pass, instant reveal…) and daily-cap status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description entitlements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entitlements?: components["schemas"]["Entitlement"][];
                            dailyLeft?: {
                                [key: string]: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue of paid services (mirrors economy ServiceKind) with live quotes in every currency */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description catalogue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            services?: components["schemas"]["Service"][];
                            solUsd?: number;
                            skrUsd?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind a paid ServicePaid event to an entitlement payload (skins → asset, theme id, emote pack id, …) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        signature: string;
                        kind: number;
                        /** @description canonical JSON; keccak(kind ‖ wallet ‖ canonical(payload)) must equal ref_hash */
                        payload: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description entitlement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Entitlement"];
                    };
                };
                /** @description payment not found / mismatch */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog with live odds, floors, pity and caps (from GameConfig) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description catalog */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            paramsVersion?: number;
                            packs?: components["schemas"]["PackSku"][];
                            bundles?: {
                                qty?: number;
                                discountBps?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price quote + everything needed to build buy_pack
         * @description Returns SOL / SKR amount from Pyth (60 s max age) with 1 % slippage guard (SKR also applies GameConfig.skrDiscountBps), $CG/USDC amounts, the caller's effective odds (pity applied), a fresh Switchboard randomness keypair hint and the PDA set.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sku: number;
                        qty: number;
                        /** @enum {string} */
                        currency: "SOL" | "USDC" | "CG" | "SKR";
                    };
                };
            };
            responses: {
                /** @description quote */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PackQuote"];
                    };
                };
                400: components["responses"]["Error"];
                /** @description daily cap reached */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/opens/{signature}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result of a pack open (poll after reveal; WS pushes the same payload) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    signature: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PackOpenResult"];
                    };
                };
                /** @description not revealed yet */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingPack"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provably-fair verifier — recompute a pack result from its randomness bytes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        signature: string;
                    };
                };
            };
            responses: {
                /** @description verification */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            randomnessAccount?: components["schemas"]["Pubkey"];
                            rollHex?: string;
                            pityBefore?: number;
                            effectiveOddsBps?: number[];
                            recomputed?: components["schemas"]["RolledChip"][];
                            onChain?: components["schemas"]["RolledChip"][];
                            matches?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All 10 districts with lore, art, element, mint stats, floor per rarity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Collection"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{idx}/chips/{rarity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chip archetype page (lore, art, supply, floor, recent sales) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    idx: number;
                    rarity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description archetype */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChipArchetype"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chips/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single chip — state, owner, listing, provenance (pack/fusion event) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset: components["schemas"]["Pubkey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description chip */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChipDetail"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active listings with filters */
        get: {
            parameters: {
                query?: {
                    collection?: number;
                    rarity?: number;
                    rarityMin?: number;
                    indexMin?: number;
                    indexMax?: number;
                    levelMin?: number;
                    currency?: "SOL" | "USDC" | "SKR";
                    priceMaxUsd?: number;
                    /** @description auth required; only chips that complete one of my sets */
                    missingForMySet?: boolean;
                    sort?: "price_asc" | "price_desc" | "newest" | "rarity_desc" | "index_asc";
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description listings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/floor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Floor matrix 10×9 (USD-normalized) + 24 h volume; cached 30 s */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description floors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            asOf?: string;
                            solUsd?: number;
                            skrUsd?: number;
                            floors?: (number | null)[][];
                            listedCount?: number[][];
                            volume24hUsd?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sales history (per chip, archetype, or global) */
        get: {
            parameters: {
                query?: {
                    asset?: components["schemas"]["Pubkey"];
                    collection?: number;
                    rarity?: number;
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalePage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offers made by me / received on my chips */
        get: {
            parameters: {
                query?: {
                    direction?: "made" | "received";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description offers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Offer"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fusion/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All 8 recipes (rule, success %, fee, lock) — mirrors on-chain constants */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description recipes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recipe"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fusion/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a material set, return success %, fee, result preview and accounts for `fuse` */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        materials: components["schemas"]["Pubkey"][];
                        resultCollection?: number;
                        useBooster?: boolean;
                    };
                };
            };
            responses: {
                /** @description plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FusionPlan"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fusion/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auto-pick fusable triples from my inventory (never touches staked/listed/locked/set-critical chips) */
        get: {
            parameters: {
                query?: {
                    protectSets?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description suggestions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FusionPlan"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enter matchmaking with a squad + seed commit */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        squad: components["schemas"]["Pubkey"][];
                        /** @description hex sha256(nonce) */
                        commit: string;
                        wagerCgMicro?: string;
                    };
                };
            };
            responses: {
                /** @description queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ticket?: string;
                            league?: number;
                            squadPower?: number;
                            estimatedWaitSec?: number;
                            wsChannel?: string;
                        };
                    };
                };
                /** @description already queued / chip busy / cap reached */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Leave queue */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/matches/{id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal seed nonce (both players) → server resolves and streams rounds over WS */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nonce: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/matches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match record incl. seed derivation (auditable after season secret reveal) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description match */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Match"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My rating, league, streak, daily rewarded matches left, wager battles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArenaMe"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/seasons/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season timer, pool size, payout brackets, my projected bracket */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description season */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Season"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deterministic fight preview for the squad builder (no rewards; same engine as live) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        squadA: components["schemas"]["Pubkey"][];
                        squadB: components["schemas"]["Pubkey"][];
                    };
                };
            };
            responses: {
                /** @description win probability + sample rounds */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pWinA?: number;
                            powerA?: number;
                            powerB?: number;
                            elementEdges?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staking/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pools (TVL, weight, today's budget), implied APY per tier, emission day stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StakingOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staking/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My token stakes, chip stakes, pending rewards (computed off acc_reward_per_weight), set bonus status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description mine */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StakingMe"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staking/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** APY estimate for an amount/tier given current pool weight */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        amountCgMicro: string;
                        tier: number;
                    };
                };
            };
            responses: {
                /** @description estimate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            apyPct?: number;
                            dailyCgMicro?: string;
                            /** Format: date-time */
                            unlockAt?: string;
                            earlyExitPenaltyBps?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active quests with my progress; eligibility flags (account age, paid pack, caps) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description quests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Quest"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quests/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Claimable Merkle leaves (root, amount, proof). `currency` follows the root kind — 2..4 pay $CG via `claim_root`, 5..7 pay SKR via `claim_skr_root` */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description claims */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimLeaf"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/skr-pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SKR prize-pool ledger (funded / withdrawn / paid / reserved) and live SKR roots — public proof that SKR rewards never exceed treasury funding */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description pool */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkrPool"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quests/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily streak state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description streak */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            days?: number;
                            nextChipAt?: number;
                            /** Format: date-time */
                            resetsAt?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/{board}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season rating / collection score / staking weight / fusion count boards */
        get: {
            parameters: {
                query?: {
                    season?: number;
                    /** @description opaque pagination cursor */
                    cursor?: components["parameters"]["cursor"];
                };
                header?: never;
                path: {
                    board: "rating" | "collection" | "staking" | "fusion";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description rows */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current on-chain GameConfig + EmissionState + history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description params */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Propose a params change → validates guard-rails → creates Squads proposal (48 h timelock) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        packs?: components["schemas"]["PackSku"][];
                        marketFeeBps?: number;
                        featuredCollection?: number;
                        emissionSplitBps?: number[];
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description proposal created */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description guard-rail violation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the economy model (packages/economy) with overridden assumptions/params */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description report json */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause a program (chip_core / staking / arena) — 2 admin approvals */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        program: string;
                        paused: boolean;
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fraud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fraud signals queue */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description rows */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fraud/{wallet}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve — ignore / shadow ban / pause rewards / ban (audited) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wallet: components["schemas"]["Pubkey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PRD KPI dashboard (D1/D7/D30, ARPPU, conversion, sink ratio, floor index) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description kpi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Pubkey: string;
        /** @description 0 Common … 8 Diamond */
        Rarity: number;
        WalletProfile: {
            address?: components["schemas"]["Pubkey"];
            handle?: string;
            avatarAsset?: components["schemas"]["Pubkey"];
            /** Format: date-time */
            firstSeen?: string;
            country?: string;
        };
        Me: components["schemas"]["WalletProfile"] & {
            balances?: {
                lamports?: string;
                usdc?: string;
                cg?: string;
                skr?: string;
            };
            pity?: {
                counters?: number[];
                toGuarantee?: number[];
                boughtToday?: number[];
                starterClaimed?: boolean;
            };
            boosters?: number;
            flags?: {
                rewardsPaused?: boolean;
                geoRestricted?: boolean;
                accountAgeH?: number;
                hasPaidPack?: boolean;
            };
            completedSets?: number;
        };
        Chip: {
            asset?: components["schemas"]["Pubkey"];
            owner?: components["schemas"]["Pubkey"];
            collection?: number;
            rarity?: components["schemas"]["Rarity"];
            level?: number;
            index?: number;
            flags?: {
                staked?: boolean;
                listed?: boolean;
                fusing?: boolean;
                soulbound?: boolean;
            };
            /** Format: date-time */
            lockUntil?: string | null;
            power?: number;
            stakeWeight?: string;
            art?: {
                /** Format: uri */
                image?: string;
                /** Format: uri */
                video?: string;
                vfxTier?: number;
            };
            listing?: components["schemas"]["Listing"];
        };
        ChipPage: {
            items?: components["schemas"]["Chip"][];
            nextCursor?: string | null;
            total?: number;
        };
        ChipDetail: components["schemas"]["Chip"] & {
            provenance?: {
                origin?: string;
                signature?: string;
                rollHex?: string;
                recipe?: number;
            };
            sales?: components["schemas"]["Sale"][];
            archetype?: components["schemas"]["ChipArchetype"];
        };
        ChipArchetype: {
            collection?: number;
            rarity?: components["schemas"]["Rarity"];
            name?: string;
            lore?: string;
            rim?: string;
            supply?: number;
            floorUsd?: number | null;
            listed?: number;
            basePower?: number;
            maxLevel?: number;
        };
        Collection: {
            idx?: number;
            symbol?: string;
            name?: string;
            /** @enum {string} */
            element?: "paint" | "steel" | "wheels" | "noise" | "shadow";
            palette?: string[];
            lore?: string;
            minted?: number;
            mintedByRarity?: number[];
            floors?: (number | null)[];
            featured?: boolean;
        };
        PackSku: {
            sku?: number;
            name?: string;
            chips?: number;
            priceUsdCents?: number;
            priceCgMicro?: string | null;
            currencies?: ("SOL" | "USDC" | "CG" | "SKR")[];
            oddsBps?: number[];
            floor?: components["schemas"]["Rarity"];
            dailyCap?: number | null;
            pity?: {
                tier?: number;
                softStart?: number;
                softStepBps?: number;
                hardAt?: number;
            } | null;
            /** @enum {string} */
            pool?: "all" | "featured";
            enabled?: boolean;
            pAtLeastLegend?: number;
            evPct?: number;
        };
        PackQuote: {
            sku?: number;
            qty?: number;
            currency?: string;
            /** @description lamports / micro-USDC / micro-CG / micro-SKR incl. bundle (and SKR promo) discount */
            amount?: string;
            /** @description amount × 1.01 for SOL and SKR; slippage guard passed to buy_pack (max_lamports = max units of the volatile currency) */
            maxLamports?: string;
            rentReserveLamports?: string;
            solUsd?: number;
            /** @description Pyth SKR/USD at quote time (only for currency=SKR) */
            skrUsd?: number;
            /** @description total discount applied (bundle + SKR promo) */
            discountBps?: number;
            priceUpdateAccount?: components["schemas"]["Pubkey"];
            /** @description base64 VAAs to post in the same tx */
            pythUpdateData?: string[];
            effectiveOddsBps?: number[];
            pityCounter?: number;
            hardPityIn?: number;
            nonce?: string;
            accounts?: {
                [key: string]: components["schemas"]["Pubkey"];
            };
            switchboardQueue?: components["schemas"]["Pubkey"];
            /** Format: date-time */
            expiresAt?: string;
        };
        RolledChip: {
            rarity?: components["schemas"]["Rarity"];
            collection?: number;
        };
        Service: {
            id?: string;
            kind?: number;
            name?: string;
            priceUsdCents?: number;
            dailyCap?: number;
            recurring?: boolean;
            /** @description amount in base units per currency (SOL lamports incl. 1 % guard, USDC, CG, SKR) */
            quotes?: {
                [key: string]: string;
            };
        };
        Entitlement: {
            id?: string;
            kind?: number;
            payload?: {
                [key: string]: unknown;
            };
            signature?: string;
            currency?: string;
            amount?: string;
            /** Format: date-time */
            grantedAt?: string;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        PendingPack: {
            nonce?: string;
            sku?: number;
            qty?: number;
            opened?: number;
            commitSlot?: number;
            currentSlot?: number;
            randomness?: components["schemas"]["Pubkey"];
            /** @enum {string} */
            status?: "awaiting_reveal" | "revealing" | "opening" | "stale";
            /** Format: date-time */
            staleAt?: string;
        };
        PendingFusion: {
            nonce?: string;
            recipe?: number;
            materials?: components["schemas"]["Pubkey"][];
            boosted?: boolean;
            status?: string;
        };
        PackOpenResult: {
            signature?: string;
            sku?: number;
            chips?: components["schemas"]["Chip"][];
            rollHex?: string;
            pityBefore?: number;
            pityAfter?: number;
            highlights?: {
                bestRarity?: components["schemas"]["Rarity"];
                newForSet?: number[];
                completedSet?: number | null;
            };
        };
        Listing: {
            asset?: components["schemas"]["Pubkey"];
            seller?: components["schemas"]["Pubkey"];
            price?: string;
            /** @enum {string} */
            currency?: "SOL" | "USDC" | "SKR";
            priceUsd?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ListingPage: {
            items?: (components["schemas"]["Listing"] & {
                chip?: components["schemas"]["Chip"];
            })[];
            nextCursor?: string | null;
            total?: number;
        };
        Sale: {
            asset?: components["schemas"]["Pubkey"];
            seller?: components["schemas"]["Pubkey"];
            buyer?: components["schemas"]["Pubkey"];
            price?: string;
            currency?: string;
            priceUsd?: number;
            fee?: string;
            royalty?: string;
            signature?: string;
            /** Format: date-time */
            blockTime?: string;
        };
        SalePage: {
            items?: components["schemas"]["Sale"][];
            nextCursor?: string | null;
        };
        Offer: {
            asset?: components["schemas"]["Pubkey"];
            bidder?: components["schemas"]["Pubkey"];
            amountUsdc?: string;
            /** Format: date-time */
            expiresAt?: string;
            chip?: components["schemas"]["Chip"];
        };
        Recipe: {
            from?: components["schemas"]["Rarity"];
            to?: components["schemas"]["Rarity"];
            /** @enum {string} */
            rule?: "any" | "same-collection";
            successBps?: number;
            refundOnFail?: number;
            feeCgMicro?: string;
            resultLockSeconds?: number;
            boosterBonusBps?: number;
            boosterCapBps?: number;
        };
        FusionPlan: {
            materials?: components["schemas"]["Chip"][];
            recipe?: components["schemas"]["Recipe"];
            resultCollection?: number;
            resultRarity?: components["schemas"]["Rarity"];
            successBps?: number;
            feeCgMicro?: string;
            breaksSet?: boolean;
            warnings?: string[];
            nonce?: string;
            accounts?: {
                [key: string]: components["schemas"]["Pubkey"];
            };
            needsRandomness?: boolean;
        };
        Match: {
            id?: string;
            season?: number;
            a?: components["schemas"]["Pubkey"];
            b?: components["schemas"]["Pubkey"];
            squadA?: components["schemas"]["Chip"][];
            squadB?: components["schemas"]["Chip"][];
            commitA?: string;
            commitB?: string;
            nonceA?: string;
            nonceB?: string;
            seed?: string;
            rounds?: {
                attacker?: string;
                defender?: string;
                elementEdge?: number;
                luckA?: number;
                luckB?: number;
                winner?: string;
            }[];
            winner?: components["schemas"]["Pubkey"];
            wagerCgMicro?: string;
            battlePda?: components["schemas"]["Pubkey"];
            resolveSignature?: string;
            rewarded?: boolean;
        };
        ArenaMe: {
            rating?: number;
            rd?: number;
            league?: number;
            games?: number;
            wins?: number;
            streak?: number;
            rewardedMatchesLeft?: number;
            seasonRank?: number;
            projectedBracket?: string;
            openBattles?: Record<string, never>[];
        };
        Season: {
            id?: number;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            poolCgMicro?: string;
            brackets?: {
                topPct?: number;
                sharePct?: number;
            }[];
            serverSecretHash?: string;
            serverSecret?: string | null;
        };
        StakingOverview: {
            emission?: {
                dayIndex?: number;
                year?: number;
                scheduleCapMicro?: string;
                guardedMicro?: string;
                burn7dAvgMicro?: string;
                mintedTotalMicro?: string;
                splitBps?: number[];
            };
            tokenPool?: {
                tvlMicro?: string;
                totalWeight?: string;
                budgetTodayMicro?: string;
                apyByTier?: number[];
            };
            chipPool?: {
                stakedChips?: number;
                totalWeight?: string;
                budgetTodayMicro?: string;
                dailyPerWeightUnit?: string;
            };
        };
        StakingMe: {
            tokenStakes?: {
                tier?: number;
                amount?: string;
                weight?: string;
                pending?: string;
                /** Format: date-time */
                unlockAt?: string;
                earlyExitPenalty?: string;
            }[];
            chipStakes?: {
                chip?: components["schemas"]["Chip"];
                weight?: string;
                pending?: string;
                /** Format: date-time */
                since?: string;
            }[];
            setBonus?: {
                onChainSets?: number;
                computedSets?: number;
                multBps?: number;
                syncPending?: boolean;
            };
            totalPendingMicro?: string;
        };
        Quest: {
            id?: string;
            cadence?: string;
            title?: string;
            description?: string;
            metric?: string;
            target?: number;
            value?: number;
            rewardCgMicro?: string;
            rewardChip?: Record<string, never> | null;
            rewardBooster?: number;
            completedAt?: string | null;
            claimable?: boolean;
            ineligibleReason?: string | null;
            /** Format: date-time */
            resetsAt?: string;
        };
        ClaimLeaf: {
            /** @description 2 quests · 3 PvP season · 4 events ($CG, minted from emission) · 5 quests · 6 season · 7 events (SKR, prize pool) */
            kind?: number;
            epoch?: number;
            /** @enum {string} */
            currency?: "CG" | "SKR";
            rootPda?: components["schemas"]["Pubkey"];
            amountMicro?: string;
            proof?: string[];
            /** Format: date-time */
            claimableAt?: string;
            claimed?: boolean;
        };
        SkrPool: {
            fundedTotalMicro?: string;
            withdrawnTotalMicro?: string;
            paidTotalMicro?: string;
            /** @description budget locked in live (non-revoked) roots minus what was already claimed */
            reservedMicro?: string;
            /** @description funded − withdrawn − paid − reserved; what new roots can still draw */
            budgetMicro?: string;
            maxRootBudgetMicro?: string | null;
            paused?: boolean;
            roots?: {
                kind?: number;
                epoch?: number;
                budgetMicro?: string;
                claimedMicro?: string;
                revoked?: boolean;
                slot?: number;
            }[];
            /** @description Treasury funding policy audit — realised SKR revenue (opened packs, settled SKR sales' treasury fee part, SKR services) × published shares (15 / 10 / 5 %) vs. what was actually funded */
            funding?: {
                treasuryWallet?: components["schemas"]["Pubkey"];
                policyBps?: {
                    packRevenue?: number;
                    marketFeeTreasury?: number;
                    servicesRevenue?: number;
                };
                cadence?: string;
                revenue?: {
                    packRevenueMicro?: string;
                    marketFeeTreasuryMicro?: string;
                    servicesRevenueMicro?: string;
                };
                /** @description Σ revenue × share — what the policy says should have been funded to date */
                dueMicro?: string;
                dueBreakdownMicro?: {
                    packs?: string;
                    market?: string;
                    services?: string;
                };
                /** @description fundedTotal − due; negative means the treasury is behind on the published policy */
                surplusMicro?: string;
            };
        };
        LeaderboardPage: {
            board?: string;
            season?: number;
            me?: Record<string, never> | null;
            items?: {
                rank?: number;
                wallet?: components["schemas"]["Pubkey"];
                handle?: string;
                value?: number;
                league?: number;
                avatar?: string;
            }[];
            nextCursor?: string | null;
        };
        ActivityPage: {
            items?: {
                kind?: string;
                signature?: string;
                /** Format: date-time */
                blockTime?: string;
                payload?: unknown;
            }[];
            nextCursor?: string | null;
        };
    };
    responses: {
        /** @description error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    code?: string;
                    message?: string;
                    details?: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description opaque pagination cursor */
        cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
