"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GEN_MARK = void 0;
// Every env var the code reads must appear in the matching `.env.example` — that is the difference
// between "deploy is a config task" and "deploy is archaeology" (docs/09 §1.4: `backend/.env.example`
// did not exist at all, while the API reads ~80 of them).
//
// `--check`  : fail on a name the code reads but the example does not document, or one the example
//              documents and nothing reads (both directions matter: the second one is what a reviewer
//              pastes into a deploy that then silently ignores it).
// `--write`  : append missing names under an `# (auto)` marker with the default extracted from the
//              source, so `npm run env:example` regenerates the file after a config change and humans
//              keep the comments.
const node_fs_1 = require("node:fs");
const node_path_1 = __importDefault(require("node:path"));
const ROOT = node_path_1.default.resolve(import.meta.dirname, '..');
const TARGETS = [
    { example: 'backend/.env.example', dirs: ['backend/src'], files: [], prefixes: [''], skipVite: true, patterns: [/\benv\.([A-Z][A-Z0-9_]{2,})\b/g, /\bprocess\.env\.([A-Z][A-Z0-9_]{2,})\b/g] },
    // the client's `loadEnv` lives in vite.config.ts, so that file is part of the readable surface too
    { example: 'client/.env.example', dirs: ['client'], files: [], prefixes: ['VITE_'], skipVite: false, patterns: [/\benv\.VITE_([A-Z0-9_]+)\b/g, /\bimport\.meta\.env\.VITE_([A-Z0-9_]+)\b/g, /\bVITE_([A-Z0-9_]+)/g] },
    // the pusher is the upstream Pyth image: no in-repo code reads these, the compose file does
    { example: 'ops/pyth-pusher/.env.example', dirs: [], files: ['ops/pyth-pusher/docker-compose.yaml', 'ops/pyth-pusher/price-config.yaml'], prefixes: [''], skipVite: false, patterns: [/\$\{([A-Z][A-Z0-9_]{2,})[:?]?[^}]*\}/g, /^\s*([A-Z][A-Z0-9_]{2,}):/gm] },
    // compose's own interpolation surface: a `${VAR}` with no default in the compose file is a deploy that
    // fails with "VAR is required" — or, worse with `:-`, a deploy that quietly uses an empty string.
    // `manual` means the file is maintained by hand (it is the deploy contract), so `--write` skips it.
    { example: 'ops/deploy/.env.example', dirs: [], files: ['ops/deploy/docker-compose.yaml'], prefixes: [''], skipVite: false, patterns: [/\$\{([A-Z][A-Z0-9_]{2,})[:?]?[^}]*\}/g], manual: true },
];
exports.GEN_MARK = '# --- generated by `npm run env:example` — do not edit below this line ---';
/** Runtime-provided, not application config — documenting these in an env example is how people start
 *  pasting `PATH=` into a deploy file. The Pyth/Switchboard/CI-facing ones stay, they are config. */
const IGNORE = new Set(['NODE_ENV', 'PATH', 'HOME', 'USER', 'CI', 'FORCE_COLOR', 'TZ', 'DEBUG', 'SHELL', 'PWD', 'LANG', 'TERM', 'NODE_OPTIONS', 'DISPLAY', 'CI_ENVIRONMENT']);
/** `env.FOO ?? 'x'`, `Number(env.FOO ?? 3)`, `(env.FOO ?? 'a').…`, `env.FOO === '1'`. */
const DEFAULT_NEAR = (name) => new RegExp(`env\\.${name}\\s*(?:\\?\\?\\s*(?:'([^']*)'|"([^"]*)"|(\\[[^\\]]*]|[^)\\n,;]+))|\\s*===\\s*'([^']*)')`, 'g');
/** `Number(env.X ?? 5 * 60_000)` has no *literal* default — reporting `5` as the default would be a lie. */
function literalDefault(src, name) {
    const re = new RegExp(`(?:env|process\\.env)\\.${name}\\s*(?:\\s+as\\s+[^|;)]+?)?\\s*(?:\\?\\?|\\|\\|)\\s*`, 'g');
    let m;
    while ((m = re.exec(src))) {
        const rest = src.slice(m.index + m[0].length);
        // Every alternative is anchored: an unanchored `\"([^\"]*)\"` here once matched a quoted word in a
        // comment 20 lines below the default and printed it as the documented value. A default is what
        // follows `??`, or it is not a default.
        const lit = /^'([^']*)'|^\"([^\"]*)\"|^(\[[^\]]*\])|^(true|false)|^(-?\d[\w.]*)/.exec(rest);
        if (!lit)
            return undefined;
        const raw = (lit[1] ?? lit[2] ?? lit[3] ?? lit[4] ?? lit[5] ?? '').trim().replace(/_(?=\d)/g, '').replace(/n(?=$|[\s,\)\]])/, '');
        const after = rest.slice((lit[0] ?? '').length).trimStart();
        // `Number(env.X ?? 15 * 60)` — an arithmetic default is still a default; evaluate it when the
        // expression is nothing but numbers and operators, and give up (blank) the moment it is not.
        const expr = /^[*+\/-]\s*[\d_]+[nN]?(?:\s*[*+\/-]\s*[\d_]+[nN]?)*\)/.exec(after);
        if (expr && lit[5] !== undefined) {
            const src2 = expr[0].slice(0, -1).replace(/_/g, '').replace(/[nN]/g, '');
            if (/^[\d*+\/-\s]+$/.test(src2)) {
                try {
                    return String(Function(`return (${lit[5]}${src2})`)());
                }
                catch { /* not a pure number */ }
            }
        }
        if (/^(<<|>>|\*|\/|\+|-)/.test(after) && lit[5] !== undefined)
            return undefined; // expression, not a literal
        return raw;
    }
    return undefined;
}
function tsFiles(dir) {
    const abs = node_path_1.default.join(ROOT, dir);
    if (!(0, node_fs_1.existsSync)(abs))
        return [];
    const out = [];
    for (const e of (0, node_fs_1.readdirSync)(abs, { withFileTypes: true })) {
        if (e.name === 'node_modules' || e.name.startsWith('.'))
            continue;
        const p = node_path_1.default.join(abs, e.name);
        if (e.isDirectory())
            out.push(...tsFiles(node_path_1.default.relative(ROOT, p)));
        else if (/\.(ts|tsx)$/.test(e.name))
            out.push(p);
    }
    return out;
}
function scan(t) {
    const found = new Map();
    const files = [...t.dirs.flatMap((d) => tsFiles(d)), ...t.files.map((f) => node_path_1.default.join(ROOT, f))];
    {
        for (const file of files) {
            // A listed source that does not exist is not drift: `tsFiles` already treats a missing directory
            // that way, and the deploy compose is optional in the tree. Throwing here made CI red for a file
            // that legitimately lands in a later commit.
            if (!(0, node_fs_1.existsSync)(file))
                continue;
            const src = (0, node_fs_1.readFileSync)(file, 'utf8');
            for (const re of t.patterns) {
                for (const m of src.matchAll(new RegExp(re.source, re.flags))) {
                    const name = m[1];
                    if (found.has(name) || IGNORE.has(name))
                        continue;
                    const rel = node_path_1.default.relative(ROOT, file);
                    const full = t.prefixes[0] === 'VITE_' && !name.startsWith('VITE_') ? `VITE_${name}` : name;
                    // The backend never reads a VITE_ var (that is the client's namespace), and the deploy file is
                    // the only other place a VITE_ name legitimately appears — so only the backend skips them.
                    if ('skipVite' in t && t.skipVite && full.startsWith('VITE_'))
                        continue;
                    const def = literalDefault(src, full) ?? literalDefault(src, name);
                    found.set(full, { name: full, file: rel, default: def });
                }
            }
        }
    }
    return found;
}
void DEFAULT_NEAR;
function documented(examplePath) {
    const abs = node_path_1.default.join(ROOT, examplePath);
    if (!(0, node_fs_1.existsSync)(abs))
        return new Set();
    const out = new Set();
    for (const line of (0, node_fs_1.readFileSync)(abs, 'utf8').split('\n')) {
        const m = /^\s*(#)?\s*([A-Z][A-Z0-9_]{2,})\s*=/.exec(line);
        if (m?.[2] && !/^\s*#\s*(example|note|see|old|deprecated)/i.test(line))
            out.add(m[2]);
    }
    return out;
}
const mode = process.argv[2] === '--write' ? 'write' : 'check';
let problems = 0;
for (const t of TARGETS) {
    const found = scan(t);
    const doc = documented(t.example);
    const missing = [...found.values()].filter((r) => !doc.has(r.name));
    const stale = [...doc].filter((n) => !found.has(n));
    if (mode === 'write') {
        if ('manual' in t && t.manual) {
            console.log(`= ${t.example}: hand-maintained, skipped by --write`);
            continue;
        }
        const abs = node_path_1.default.join(ROOT, t.example);
        const body = (0, node_fs_1.existsSync)(abs) ? (0, node_fs_1.readFileSync)(abs, 'utf8') : '';
        const cut = body.indexOf(exports.GEN_MARK);
        const head = (cut >= 0 ? body.slice(0, cut) : body).replace(/\n+$/, '');
        const rows = [...found.values()];
        const byFile = new Map();
        for (const r of rows) {
            const a = byFile.get(r.file) ?? [];
            a.push(r);
            byFile.set(r.file, a);
        }
        const block = [...byFile.entries()].sort().map(([file, list]) => `# ---- ${file} ----\n` + list.map((r) => `${r.name}=${r.default ?? ''}${r.default === undefined ? '    # no literal default in code' : ''}`).join('\n')).join('\n\n');
        (0, node_fs_1.writeFileSync)(abs, `${head}\n\n${exports.GEN_MARK}\n# Values are the code's own defaults: this file lists everything readable, not everything to\n# change. Prose goes above the marker; the block below it is generated by \`npm run env:example\`.\n${block}\n`);
        console.log(`${t.example}: ${rows.length} var(s) regenerated`);
        continue;
    }
    if (missing.length) {
        problems += missing.length;
        console.log(`✗ ${t.example} is missing ${missing.length} var(s) the code reads:`);
        for (const r of missing.slice(0, 40))
            console.log(`    ${r.name}${r.default !== undefined ? ` (default ${JSON.stringify(r.default)})` : ''} — ${r.file}`);
    }
    if (stale.length) {
        problems += stale.length;
        console.log(`✗ ${t.example} documents ${stale.length} var(s) nothing reads: ${stale.join(', ')}`);
    }
    if (!missing.length && !stale.length)
        console.log(`✓ ${t.example} — ${found.size} var(s) documented, 0 drift`);
}
if (problems) {
    console.log(`\n${problems} env drift(s). Run: npm run env:example`);
    process.exit(1);
}
