  // ---------------------------------------------------------------------
  // LINKS — the only place to edit before launch. '#' renders as a dead,
  // visibly disabled link on purpose: no handle is linked before we own it.
  // ---------------------------------------------------------------------
  const LINKS = {
    app: 'https://app.guttercaps.gg',
    api: 'https://api.guttercaps.gg/v1',
    telegram: '#', x: '#', discord: '#', docs: '#', github: '#',
  };
  // The legal documents are served by the app itself (client/src/features/legal/), so they are derived
  // from `app` rather than written out again: at launch the domain changes in exactly one place, and a
  // ToS link left on the old host is the kind of bug a store rejection is filed for.
  for (const [key, path] of [['terms', '/legal/terms'], ['privacy', '/legal/privacy']]) {
    LINKS[key] = LINKS.app + path;
  };
  document.querySelectorAll('[data-link]').forEach((a) => {
    const href = LINKS[a.dataset.link];
    if (href && href !== '#') { a.href = href; return; }
    a.setAttribute('aria-disabled', 'true');
    a.title = 'coming soon';
    a.addEventListener('click', (e) => e.preventDefault());
  });

  function fireSpray(btn) {
    btn.classList.add('fired');
    setTimeout(() => btn.classList.remove('fired'), 400);
  }

  // Ambient cursor/touch paint trail — throttled, off for reduced motion.
  (function () {
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    const colors = ['#FF2E8A', '#16E5D9', '#B6FF3C', '#FF7A1A'];
    let last = 0;
    function spawn(x, y) {
      const dot = document.createElement('div');
      dot.className = 'paint-dot';
      dot.style.left = (x - 2) + 'px'; dot.style.top = (y - 2) + 'px';
      dot.style.background = colors[Math.floor(Math.random() * colors.length)];
      document.body.appendChild(dot);
      setTimeout(() => dot.remove(), 700);
    }
    function onMove(x, y) { const now = performance.now(); if (now - last < 45) return; last = now; spawn(x, y); }
    window.addEventListener('mousemove', (e) => onMove(e.clientX, e.clientY), { passive: true });
    window.addEventListener('touchmove', (e) => { const t = e.touches[0]; if (t) onMove(t.clientX, t.clientY); }, { passive: true });
  })();

  // Hero letters spray in one by one.
  (function () {
    const el = document.getElementById('hero-title');
    'GUTTERCAPS'.split('').forEach((ch, i) => {
      const span = document.createElement('span');
      span.className = 'spray-letter' + (i >= 6 ? ' accent' : '');
      span.style.animationDelay = (i * 55) + 'ms';
      span.textContent = ch;
      el.appendChild(span);
    });
  })();

  // Street-lamp bulbs inside every glow.
  (function () {
    document.querySelectorAll('.lamp-glow').forEach((glow) => {
      const bulb = document.createElement('div');
      bulb.className = 'lamp-bulb';
      const rect = glow.style.background.match(/rgba?\(([^)]+)\)/);
      bulb.style.color = rect ? 'rgba(' + rect[1].split(',').slice(0, 3).join(',') + ',1)' : '#fff';
      bulb.style.left = '50%'; bulb.style.top = '50%';
      glow.appendChild(bulb);
    });
  })();

  // ---------------------------------------------------------------------
  // Data — generated by scripts/landing/build.py from content.py, which
  // mirrors packages/economy (checked by scripts/landing/check.py).
  // ---------------------------------------------------------------------
  /*__DATA__*/

  // ---------------------------------------------------------------------
  // i18n — EN is inline in the markup, RU is a dictionary keyed by
  // data-i18n. The other five app languages (PT/ES/VI/ID/FIL) land here
  // after native review; the app itself already ships all seven.
  // ---------------------------------------------------------------------
  let LANG = 'en';
  const EN = {};
  document.querySelectorAll('[data-i18n],[data-i18n-html]').forEach((el) => {
    const k = el.dataset.i18n || el.dataset.i18nHtml;
    EN[k] = el.dataset.i18nHtml !== undefined ? el.innerHTML : el.textContent;
  });
  EN['meta.title'] = document.title;
  const metaDesc = document.querySelector('meta[name="description"]');
  EN['meta.desc'] = metaDesc ? metaDesc.content : '';

  function detectLang() {
    const q = new URLSearchParams(location.search).get('lang');
    if (q === 'ru' || q === 'en') return q;
    try { const s = localStorage.getItem('gc.landing.lang'); if (s === 'ru' || s === 'en') return s; } catch (e) { /* private mode */ }
    return (navigator.language || '').toLowerCase().startsWith('ru') ? 'ru' : 'en';
  }

  function tr(k) { return (LANG === 'ru' && RU[k] !== undefined) ? RU[k] : EN[k]; }

  function setLang(lang) {
    LANG = lang === 'ru' ? 'ru' : 'en';
    document.documentElement.lang = LANG;
    document.querySelectorAll('[data-i18n],[data-i18n-html]').forEach((el) => {
      const k = el.dataset.i18n || el.dataset.i18nHtml;
      const v = tr(k);
      if (v === undefined) return;
      if (el.dataset.i18nHtml !== undefined) el.innerHTML = v; else el.textContent = v;
    });
    document.title = tr('meta.title');
    if (metaDesc) metaDesc.content = tr('meta.desc');
    document.querySelectorAll('.lang-toggle button').forEach((b) => b.setAttribute('aria-pressed', String(b.dataset.lang === LANG)));
    try { localStorage.setItem('gc.landing.lang', LANG); } catch (e) { /* ignore */ }
    renderHowto();
    renderPacks();
    renderStats(lastStats);
  }
  document.querySelectorAll('.lang-toggle button').forEach((b) => b.addEventListener('click', () => setLang(b.dataset.lang)));

  function hexToRgba(hex, a) {
    const v = hex.replace('#', '');
    const n = parseInt(v.length === 3 ? v.split('').map((c) => c + c).join('') : v, 16);
    return 'rgba(' + ((n >> 16) & 255) + ',' + ((n >> 8) & 255) + ',' + (n & 255) + ',' + a + ')';
  }

  function renderHowto() {
    const wrap = document.getElementById('howto');
    wrap.innerHTML = HOWTO.map((s, i) => {
      const [h, p, f] = s[LANG] || s.en;
      return '<li class="step" style="--step-color:' + s.color + ';--step-glow:' + s.glow + '">' +
        '<div class="step-num" aria-hidden="true">' + (i + 1) + '</div><h3>' + h + '</h3><p>' + p + '</p><span class="step-fact">' + f + '</span></li>';
    }).join('');
  }

  function renderPacks() {
    const wrap = document.getElementById('packs-grid');
    wrap.innerHTML = PACKS.map((p) => {
      const [name, tag, lines] = p[LANG] || p.en;
      const alt = p.cg ? (LANG === 'ru' ? 'или ' : 'or ') + p.cg : '';
      return '<div class="pack" style="--pack-color:' + p.color + ';--pack-glow:' + p.glow + '">' +
        '<span class="pack-tag">' + tag + '</span><span class="pack-name">' + name + '</span>' +
        '<span class="pack-price">' + p.price + '<small>' + alt + '</small></span>' +
        '<ul>' + lines.map((l) => '<li>' + l + '</li>').join('') + '</ul></div>';
    }).join('');
  }

  // Charge meter — built top-down from Diamond to Common.
  (function () {
    const wrap = document.getElementById('meterRows');
    [...TIERS].reverse().forEach((t, idx) => {
      const rank = TIERS.length - 1 - idx;
      const row = document.createElement('div');
      row.className = 'meter-row' + (rank === 8 ? ' meter-row--peak' : '');
      row.style.setProperty('--tier-color', t.color);
      row.style.setProperty('--dot-size', (8 + rank * 1.6) + 'px');
      row.style.setProperty('--dot-glow', (5 + rank * 2.4) + 'px');
      row.innerHTML =
        '<span class="meter-dot"></span>' +
        '<span class="m-name" style="font-size:' + (14 + rank * 1.7) + 'px">' + t.key + '</span>' +
        '<span class="m-odds">' + t.odds + '</span>' +
        '<span class="m-level">lvl ' + t.level + '<span class="m-power">⚡ ' + t.power + ' · ⚖ ' + t.weight + '</span></span>';
      wrap.appendChild(row);
    });
  })();

  // Permit cards (rules section) — same TIERS table, no second source of truth.
  (function () {
    const wrap = document.getElementById('permitGrid');
    TIERS.forEach((t) => {
      const card = document.createElement('div');
      card.className = 'permit';
      card.style.setProperty('--p-color', t.color);
      card.innerHTML = '<div class="p-tier">' + t.key + '</div><div class="p-odds">' + t.odds + '</div><div class="p-level">lvl ' + t.level + ' · ' + t.power + '⚡</div>';
      wrap.appendChild(card);
    });
  })();

  // Live counters from the indexer (backend GET /v1/stats). Never faked:
  // if the API is unreachable the section says so.
  let lastStats = null;
  function renderStats(s) {
    const status = document.getElementById('stats-status');
    const loc = LANG === 'ru' ? 'ru-RU' : 'en-US';
    if (!s) { status.textContent = tr('stats.offline'); return; }
    document.querySelectorAll('[data-stat]').forEach((el) => {
      const v = s[el.dataset.stat];
      el.classList.remove('pending');
      el.textContent = typeof v === 'number' ? v.toLocaleString(loc) : '—';
    });
    status.textContent = (LANG === 'ru' ? 'devnet · слот ' : 'devnet · slot ') + Number(s.lastSlot || 0).toLocaleString(loc);
  }
  (function () {
    if (typeof fetch !== 'function' || typeof AbortController !== 'function') return;
    const ctrl = new AbortController();
    setTimeout(() => ctrl.abort(), 4000);
    fetch(LINKS.api + '/stats', { signal: ctrl.signal })
      .then((r) => (r.ok ? r.json() : null))
      .then((s) => { lastStats = s; renderStats(s); })
      .catch(() => renderStats(null));
  })();

  // ---------------------------------------------------------------------
  // ART SLOTS — every cap is { name, desc } and renders as a placeholder
  // ring; add an "img" field per cap when final art arrives.
  // ---------------------------------------------------------------------
/*__COLLECTIONS__*/
  (function () {
    const wrap = document.getElementById('districts');
    COLLECTIONS.forEach((col) => {
      const div = document.createElement('div');
      div.className = 'district';
      div.style.setProperty('--district-color', col.color);
      let row = '';
      col.caps.forEach((cap, i) => {
        const t = TIERS[i];
        const size = 92, glow = 6 + i * 3, rim = i === 8 ? 3 : 4;
        const circleStyle = 'width:' + size + 'px;height:' + size + 'px;--tier-color:' + t.color + ';--tier-bg:' + hexToRgba(t.color, 0.18) + ';--tier-glow:' + hexToRgba(t.color, 0.5) + ';--rim-w:' + rim + 'px;--glow:' + glow + 'px;';
        const inner = cap.img
          ? '<img src="' + cap.img + '" alt="' + cap.name + '" loading="lazy" decoding="async">'
          : '<span class="chip-mono" style="font-size:' + Math.round(size * 0.32) + 'px;">' + col.name.charAt(0) + '</span>';
        row += '<div class="chip-slot' + (i === 8 ? ' chip-slot--diamond' : '') + '">' +
          '<div class="chip-circle" style="' + circleStyle + '">' + inner + '</div>' +
          '<span class="chip-tier" style="color:' + t.color + '">' + t.key + '</span>' +
          '<span class="chip-name">' + cap.name + '</span>' +
          '<span class="chip-desc">' + cap.desc + '</span></div>';
      });
      const art = (typeof DISTRICT_ART !== 'undefined' && DISTRICT_ART[col.num])
        ? '<img class="district-art" src="' + DISTRICT_ART[col.num] + '" alt="" aria-hidden="true" loading="lazy" decoding="async" width="406" height="406">'
        : '';
      div.innerHTML =
        '<div class="district-head"><span class="district-num">' + col.num + '</span>' +
        '<div><h3 class="district-name">' + col.name + '</h3><span class="district-meta">' + col.district + ' · ' + col.theme + '</span></div></div>' +
        art +
        '<p class="district-history">' + col.history + '</p><div class="chip-row">' + row + '</div>';
      wrap.appendChild(div);
    });
  })();

  // ---------------------------------------------------------------------
  // PHOTO WALLS — backdrop reveal on scroll + cursor light in the hero.
  // Both are decorative: they switch on with JS, stay off without it, and
  // freeze entirely under prefers-reduced-motion.
  // ---------------------------------------------------------------------
  (function () {
    const photos = document.querySelectorAll('.wall-photo');
    if (!photos.length) return;
    if (matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) {
      photos.forEach((p) => p.classList.add('on'));
      return;
    }
    const io = new IntersectionObserver((entries) => entries.forEach((e) => {
      if (e.isIntersecting) { e.target.classList.add('on'); io.unobserve(e.target); }
    }), { rootMargin: '160px' });
    photos.forEach((p) => io.observe(p));
  })();

  (function () {
    const hero = document.querySelector('.hero');
    if (!hero || matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    if (hero.querySelector('.puddle-glow')) return;
    const glow = document.createElement('div');
    glow.className = 'puddle-glow';
    hero.appendChild(glow);
    let raf = 0;
    hero.addEventListener('pointermove', (e) => {
      if (raf) return;
      raf = requestAnimationFrame(() => {
        const r = hero.getBoundingClientRect();
        glow.style.setProperty('--px', (((e.clientX - r.left) / r.width) * 100).toFixed(1) + '%');
        glow.style.setProperty('--py', (((e.clientY - r.top) / r.height) * 100).toFixed(1) + '%');
        raf = 0;
      });
    }, { passive: true });
  })();

  setLang(detectLang());
